name: rt-conf
base: core24
version: git
summary: Configure and tune your real-time system
description: |
  Tool destined to configure real-time parameters in a Linux system.
  Currently let's you configure kernel commandline parameters.

grade: stable
confinement: strict

environment:
  DEFAULT_CONFIG_FILE: $SNAP_COMMON/config.yaml

parts:
  local:
    source: snap/local
    plugin: dump

  rt-conf:
    source: .
    plugin: go
    build-snaps:
      - go

  config-file:
    plugin: dump
    source: .
    stage:
      - config.yaml

plugs:
  etc-default-grub:
    interface: system-files
    write:
      - /etc/default/grub.d/60_rt-conf.cfg
    read:
      - /etc/default/grub

hooks:
  remove:
    plugs:
      - etc-default-grub

apps:
  rt-conf: &rt-conf
    plugs:
      - cpu-control
      - etc-default-grub
      - hardware-observe
      - home
    command-chain:
      - bin/export-env.sh
    command: bin/rt-conf

  # Run the same app as a oneshot service
  d:
    <<: *rt-conf
    daemon: oneshot
