#!/bin/bash

set -eu

if snapctl is-connected etc-default-grubd; then
  rm /etc/default/grub.d/60_rt-conf.cfg || true
  exit 0
fi

echo "[rt-conf snap] WARNING: The 'etc-default-grubd' plug is not connected. Please manually remove the configuration file at /etc/default/grub.d/60_rt-conf.cfg." | logger
